name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.4
            composer: '--prefer-lowest'
            desc: "Lowest versions"
          - php: 7.4
          - php: 8.0
          - php: 8.1
          - php: 8.2
            coverage: '--coverage-clover /tmp/clover.xml'
          - php: 8.3
    name: PHP ${{ matrix.php }} ${{ matrix.desc }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress ${{ matrix.composer }}

    - name: Run PHPUnit
      run: vendor/bin/phpunit ${{ matrix.coverage }}

    - name: Upload Scrutinizer coverage
      uses: sudo-bot/action-scrutinizer@latest
      if: ${{ matrix.coverage }}
      with:
        cli-args: "--format=php-clover build/logs/clover.xml --revision=${{ github.event.pull_request.head.sha || github.sha }}"
